require('elixir/logic/is_in_combat')
require('elixir/logic/is_me_high_aggro')
require('elixir/logic/is_tank_in_party')
require('elixir/logic/most_hurt_ally')
require('elixir/logic/obstruction')
require('elixir/logic/spell_tag')